version: 2
jobs:
  test-and-publish:
    docker:
      - image: cimg/python:3.13

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install python test dependencies
          command: |
            pip install -r requirements_test.txt -e .

      # run tests
      - run:
          name: Run tests
          command: |
            pytest

      - run:
          name: Package & Publish
          command: |
            # package
            python setup.py sdist
            python setup.py bdist_wheel

            if [ "${CIRCLE_BRANCH}" == "production" ] ; then
                # prepare pypirc file (using API token auth)
                echo -e "[pypi]" > ~/.pypirc
                echo -e "username = __token__" >> ~/.pypirc
                echo -e "password = $PYPI_API_TOKEN" >> ~/.pypirc

                # publish
                pip install twine
                twine upload dist/*
            else
                echo "Did not publish - not production branch!"
            fi




workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-and-publish:
          context: pypi